global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pvz-service'
    static_configs:
      - targets: ['pvz-service:9000']  # Используем имя сервиса в docker network